export const products = [
    {
        id: 1,
        title: '├ëcouteurs Bluetooth Pro Max',
        price: 49.99,
        originalPrice: 89.99,
        category: 'Audio',
        rating: 4.8,
        reviews: 2341,
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80',
        badge: 'Bestseller',
        description: 'Son cristallin, r├®duction de bruit avanc├®e, autonomie 30h.',
        affiliateLink: 'https://www.temu.com',
        inStock: true,
    },
    {
        id: 2,
        title: 'Montre Connect├®e Sport Ultra',
        price: 39.99,
        originalPrice: 79.99,
        category: 'Montres',
        rating: 4.7,
        reviews: 1892,
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80',
        badge: 'Nouveau',
        description: 'GPS int├®gr├®, ├®tanche 5ATM, suivi sant├® 24/7.',
        affiliateLink: 'https://www.temu.com',
        inStock: true,
    },
    {
        id: 3,
        title: 'Lampe LED Bureau Premium',
        price: 24.99,
        originalPrice: 45.99,
        category: 'Maison',
        rating: 4.6,
        reviews: 987,
        image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&q=80',
        badge: '-45%',
        description: 'Lumi├¿re ajustable, charge USB-C int├®gr├®e, design ├®l├®gant.',
        affiliateLink: 'https://www.temu.com',
        inStock: true,
    },
    {
        id: 4,
        title: 'Sac ├á Dos Tech Anti-Vol',
        price: 34.99,
        originalPrice: 59.99,
        category: 'Mode',
        rating: 4.9,
        reviews: 3241,
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
        badge: 'Top Vente',
        description: 'Port USB, compartiment laptop 17", mati├¿re imperm├®able.',
        affiliateLink: 'https://www.temu.com',
        inStock: true,
    },
    {
        id: 5,
        title: 'Chargeur Sans Fil 65W',
        price: 19.99,
        originalPrice: 39.99,
        category: 'Tech',
        rating: 4.5,
        reviews: 1432,
        image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400&q=80',
        badge: 'Promo',
        description: 'Compatible iPhone & Android, charge ultra-rapide.',
        affiliateLink: 'https://www.temu.com',
        inStock: true,
    },
    {
        id: 6,
        title: 'Clavier M├®canique RGB',
        price: 59.99,
        originalPrice: 99.99,
        category: 'Tech',
        rating: 4.8,
        reviews: 2108,
        image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&q=80',
        badge: 'Gaming',
        description: 'Switches blue, r├®tro├®clairage RGB, layout compact TKL.',
        affiliateLink: 'https://www.temu.com',
        inStock: true,
    },
    {
        id: 7,
        title: 'Lunettes Anti-Lumi├¿re Bleue',
        price: 14.99,
        originalPrice: 29.99,
        category: 'Mode',
        rating: 4.4,
        reviews: 876,
        image: 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400&q=80',
        badge: 'Sant├®',
        description: 'Protection oculaire, monture l├®g├¿re, verres anti-reflet.',
        affiliateLink: 'https://www.temu.com',
        inStock: true,
    },
    {
        id: 8,
        title: 'Mini Ventilateur USB-C',
        price: 12.99,
        originalPrice: 24.99,
        category: 'Maison',
        rating: 4.3,
        reviews: 654,
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
        badge: '├ët├®',
        description: '3 vitesses, pliable, silencieux, adapt├® bureau et voyage.',
        affiliateLink: 'https://www.temu.com',
        inStock: false,
    },
    {
        id: 9,
        title: 'Ïº┘äÏ»┘ä┘è┘ä Ïº┘äÏ░┘çÏ¿┘è ┘ü┘è ÏÁ┘èÏº┘åÏ® Ïú┘åÏ©┘àÏ® Ïº┘äÏ¬Ï»┘üÏªÏ® (M207)',
        price: 49.00,
        originalPrice: 99.00,
        category: 'Livres',
        rating: 5.0,
        reviews: 42,
        image: '/chauffage/img1.webp',
        badge: 'Nouveau',
        description: 'Ï»┘ä┘è┘ä Ï┤Ïº┘à┘ä ┘äÏÀ┘äÏ¿Ï® ┘êÏ¬┘é┘å┘è┘è Ïº┘ä┘ç┘åÏ»Ï│Ï® Ïº┘äÏ¡Ï▒ÏºÏ▒┘èÏ® Ï¿Ïº┘ä┘àÏ║Ï▒Ï¿ - Ï¿Ïº┘ä┘äÏ║Ï¬┘è┘å Ïº┘äÏ╣Ï▒Ï¿┘èÏ® ┘êÏº┘ä┘üÏ▒┘åÏ│┘èÏ® ÏÁ┘èÏº┘åÏ® ┘êÏÑÏÁ┘äÏºÏ¡ Ïú┘åÏ©┘àÏ® Ïº┘äÏ¬Ï»┘üÏªÏ®',
        affiliateLink: '/chauffage.html',
        inStock: true,
    }
]

export const categories = ['Tous', 'Tech', 'Audio', 'Montres', 'Maison', 'Mode', 'Livres']
